# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(171414)
$foreground = rgb(FEC8BB)
$color0 = rgb(3E3C3C)
$color1 = rgb(491F1C)
$color2 = rgb(6F261F)
$color3 = rgb(DA4A31)
$color4 = rgb(FA613C)
$color5 = rgb(FC633D)
$color6 = rgb(FC633D)
$color7 = rgb(F5A996)
$color8 = rgb(AC7669)
$color9 = rgb(491F1C)
$color10 = rgb(6F261F)
$color11 = rgb(DA4A31)
$color12 = rgb(FA613C)
$color13 = rgb(FC633D)
$color14 = rgb(FC633D)
$color15 = rgb(F5A996)
