# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1C1213)
$foreground = rgb(FEC0C8)
$color0 = rgb(443A3A)
$color1 = rgb(310307)
$color2 = rgb(310307)
$color3 = rgb(980317)
$color4 = rgb(980317)
$color5 = rgb(FB4B61)
$color6 = rgb(FB4B61)
$color7 = rgb(F59DA8)
$color8 = rgb(AB6E75)
$color9 = rgb(310307)
$color10 = rgb(310307)
$color11 = rgb(980317)
$color12 = rgb(980317)
$color13 = rgb(FB4B61)
$color14 = rgb(FB4B61)
$color15 = rgb(F59DA8)
