# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(05090C)
$foreground = rgb(D0DFEA)
$color0 = rgb(3E4042)
$color1 = rgb(78A3C3)
$color2 = rgb(78A3C3)
$color3 = rgb(30546F)
$color4 = rgb(30546F)
$color5 = rgb(30546F)
$color6 = rgb(30546F)
$color7 = rgb(B3C9D9)
$color8 = rgb(7D8C98)
$color9 = rgb(78A3C3)
$color10 = rgb(78A3C3)
$color11 = rgb(30546F)
$color12 = rgb(30546F)
$color13 = rgb(30546F)
$color14 = rgb(30546F)
$color15 = rgb(B3C9D9)
