cursor #e5e3d6
cursor_text_color #c9c7b6

foreground            #e5e3d6
background            #13140c
selection_foreground  #303219
selection_background  #c8c9a6
url_color             #c6cc79

color0   #13140c
color1   #ea7a69
color2   #71cc66
color3   #ffe972
color4   #bac163
color5   #595e17
color6   #c6cc79
color7   #d5d6c9
color8   #83847a
color9   #ffab9f
color10  #a8f49f
color11  #fff1a5
color12  #dae092
color13  #f9ffb6
color14  #fbffd0
color15  #fefff8
