# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FEC8BB
background         #171414
cursor             #B6776D

active_tab_foreground     #171414
active_tab_background     #FEC8BB
inactive_tab_foreground   #FEC8BB
inactive_tab_background   #171414

active_border_color   #FEC8BB
inactive_border_color #171414
bell_border_color     #491F1C

color0      #3E3C3C
color1		#491F1C
color2		#6F261F
color3		#DA4A31
color4		#FA613C
color5		#FC633D
color6		#FC633D
color7		#F5A996
color8		#AC7669
color9		#491F1C
color10		#6F261F
color11		#DA4A31
color12		#FA613C
color13		#FC633D
color14		#FC633D
color15		#F5A996
