# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* matugen template - colors-kitty */

foreground         #f8dcda
background         #1e100f
cursor             #ffd2ce

active_tab_foreground     #1e100f
active_tab_background     #f8dcda
inactive_tab_foreground   #f8dcda
inactive_tab_background   #1e100f

active_border_color   #f8dcda
inactive_border_color #1e100f
bell_border_color     #ffd2cc

color0      #1e100f
color1		#ffd2cc
color2		#ffd4b6
color3		#ba8470
color4		#ffd2ce
color5		#bf8354
color6		#ffd3c3
color7		#ffffff
color8		#554241
color9		#ff5449
color10		#000000
color11		#000000
color12		#000000
color13		#3e1d00
color14		#3e1c0e
color15		#f8dcda
