# vim:ft=kitty

## name: Canopy Mist
## author: sanjai
## license: MIT
## blurb: Soft green-forward dark theme tuned for leafy wallpapers. Bright enough to feel alive, but muted enough for long sessions.


#: The basic colors

foreground #e6f1e1
background #061701
selection_foreground #eef6ea
selection_background #314235


#: Cursor colors

cursor #b8d9a8
cursor_text_color #162019


#: URL underline color when hovering with mouse

url_color #93c97a


#: kitty window border colors and terminal bell colors

active_border_color #7fb36b
inactive_border_color #223026
bell_border_color #a8c67a
visual_bell_color none


#: OS Window titlebar colors

wayland_titlebar_color #223026
macos_titlebar_color #223026


#: Tab bar colors

active_tab_foreground #162019
active_tab_background #c4e4b4
inactive_tab_foreground #dce8d8
inactive_tab_background #223026
tab_bar_background #1b251d
tab_bar_margin_color none


#: Colors for marks (marked text in the terminal)

mark1_foreground #162019
mark1_background #d7e7a8
mark2_foreground #162019
mark2_background #93c97a
mark3_foreground #162019
mark3_background #74b8b0


#: The basic 16 colors

#: black
color0 #1e2820
color8 #55665a

#: red
color1 #c97a7a
color9 #e39a9a

#: green
color2 #79DB51
color10 #a6d58e

#: yellow
color3 #c7be7a
color11 #e0d38e

#: blue
color4 #7aa2c9
color12 #98bdea

#: magenta
color5 #b392c9
color13 #cfb1e1

#: cyan
color6 #74b8b0
color14 #97d2cb

#: white
color7 #89C274
color15 #f7fcf4
