foreground         #D0DFEA
background         #00141a
cursor             #8099AC

active_tab_foreground     #05090C
active_tab_background     #D0DFEA
inactive_tab_foreground   #D0DFEA
inactive_tab_background   #05090C

active_border_color   #D0DFEA
inactive_border_color #05090C
bell_border_color     #78A3C3

color0      #3E4042
color1		#78A3C3
color2		#78A3C3
color3		#30546F
color4		#30546F
color5		#30546F
color6		#30546F
color7		#B3C9D9
color8		#7D8C98
color9		#78A3C3
color10		#78A3C3
color11		#30546F
color12		#30546F
color13		#30546F
color14		#30546F
color15		#B3C9D9
