# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #AAB6B6
background         #04150B
cursor             #72948A

active_tab_foreground     #04150B
active_tab_background     #AAB6B6
inactive_tab_foreground   #AAB6B6
inactive_tab_background   #04150B

active_border_color   #AAB6B6
inactive_border_color #04150B
bell_border_color     #3A8C73

color0      #323F37
color1		#3A8C73
color2		#3A735D
color3		#2C6F5D
color4		#133835
color5		#0F3432
color6		#0C2E2E
color7		#7D8E8E
color8		#586363
color9		#3A8C73
color10		#3A735D
color11		#2C6F5D
color12		#133835
color13		#0F3432
color14		#0C2E2E
color15		#7D8E8E
