$mainMod = SUPER
$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts
$UserConfigs = $HOME/.config/hypr/UserConfigs

bind = $mainMod SHIFT, L, exec, hyprlock\

binds = Super_L, n&o, exec, kitty micro /home/kronoseus/workspace/todo.md
binds = Super_L, n&o&t, exec, kitty micro
binds = Super_L, f&i, exec, flatpak run org.mozilla.firefox  

# keymouse
binds = Control_R Alt_R, apostrophe, exec, ydotool click 0xC0   # left click
binds = Control_R Alt_R, semicolon, exec, ydotool click 0xC1    # right click
bind = Control_R Alt_R, Left, exec, touch /tmp/mk_left
bindr = Control_R Alt_R, Left, exec, rm /tmp/mk_left
bind = Control_R Alt_R, Right, exec, touch /tmp/mk_right
bindr = Control_R Alt_R, Right, exec, rm /tmp/mk_right
bind = Control_R Alt_R, Up, exec, touch /tmp/mk_up
bindr= Control_R Alt_R, Up, exec, rm /tmp/mk_up
bind = Control_R Alt_R, Down, exec, touch /tmp/mk_down
bindr = Control_R Alt_R , Down, exec, rm /tmp/mk_down



# For passthrough keyboard into a VM
# bind = $mainMod ALT, P, submap, passthru
#submap = passthru
# to unbind
#bind = $mainMod ALT, P, submap, reset
#submap = reset

