# This file is used to add or overwrite window rules 

# wlogout — blur the desktop behind the overlay
layerrule = blur on, match:namespace wlogout
layerrule = ignore_alpha 0, match:namespace wlogout
