# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates

# wlogout — blur the desktop behind the overlay
layerrule = blur on, match:namespace wlogout
layerrule = ignore_alpha 0, match:namespace wlogout
