# # /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# # wallust configuration - kitty only
# 
# backend = "fastresize"
# color_space = "labmixed"
# palette = "harddark16"
# threshold = 11
# 
# [templates]
# kitty.template = 'colors-kitty.conf'
# kitty.target = '~/.config/kitty/kitty-themes/01-Wallust.conf'
