preload = /home/kronoseus/Pictures/wallpapers/pablo-dominguez-eclipse-beaconkeyframes-b-v001-002-pd.jpg 
wallpaper = eDP-1,/home/kronoseus/Pictures/wallpapers/pablo-dominguez-eclipse-beaconkeyframes-b-v001-002-pd.jpg
