Net/ThemeName "MacTahoe-Dark-orange"
Net/IconThemeName "MacTahoe"
Gtk/CursorThemeName "default"
Net/EnableEventSounds 0
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
