#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┳┏┳┓┏┳┓┓┏
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┃┫ ┃ ┃  ┃ ┗┫
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┛┻ ┻  ┻ ┗┛
#                                


# Core Colors
background            #1a1111
foreground            #f1dedd
selection_foreground  #ffb3af
selection_background  #571d1d
cursor                #ffb3af
cursor_text_color     #1a1111

# Regular Colors
color0  #1a1111               
color1  #ffb4ab                 
color2  #ffb3af               
color3  #e2c28c              
color4  #ffdad7  
color5  #ffdad7
color6  #e7bdba             
color7  #f1dedd            

# Bright Colors
color8  #423736         
color9  #ffb4ab                  
color10 #ffb3af                
color11 #e2c28c               
color12 #ffdad7   
color13 #ffdad7 
color14 #e7bdba              
color15 #f1dedd             
