# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e5e3d6"

# Title color for boxes
theme[title]="#c6cc79"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#c8c9a6"

# Background color of selected item in processes box
theme[selected_bg]="#c6cc79"

# Foreground color of selected item in processes box
theme[selected_fg]="#2f3300"

# Color of inactive/disabled text
theme[inactive_fg]="#c9c7b6"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#a3d0c0"

# Cpu box outline color
theme[cpu_box]="#929182"

# Memory/disks box outline color
theme[mem_box]="#929182"

# Net up/down box outline color
theme[net_box]="#929182"

# Processes box outline color
theme[proc_box]="#929182"

# Box divider line and small boxes line color
theme[div_line]="#47483b"

# Temperature graph colors
theme[temp_start]="#c8c9a6"
theme[temp_mid]="#c6cc79"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#c8c9a6"
theme[cpu_mid]="#c6cc79"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#c8c9a6"
theme[free_mid]=""
theme[free_end]="#47492e"

# Mem/Disk cached meter
theme[cached_start]="#a3d0c0"
theme[cached_mid]=""
theme[cached_end]="#234e42"

# Mem/Disk available meter
theme[available_start]="#c6cc79"
theme[available_mid]=""
theme[available_end]="#454a03"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#c8c9a6"
theme[download_mid]="#c6cc79"
theme[download_end]="#a3d0c0"

# Upload graph colors
theme[upload_start]="#c8c9a6"
theme[upload_mid]="#c6cc79"
theme[upload_end]="#a3d0c0"
